[package]
name = "AgamaMirgrationServer"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
tempfile = "3.12.0"
anyhow = "1.0.87"
shlex = "1.3.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
tokio = "1.40.0"
rand = "0.8.5"
chrono = "0.4.38"
